[versions]
ant-ver = "1.10.11"
assertj-ver = "3.24.2"
avro-ver = "1.11.4"
aircompressor = "0.27"
awaitility-ver = "4.2.0"
bson-ver = "4.11.0"
commonsBeanutils-ver = "1.11.0"
commonsCompress = "1.26.0"
commons-lang3-ver = "3.18.0"
derby-ver = "10.17.1.0"
guava-ver = "32.0.0-jre"
hadoop-ver = "3.4.1"
hive-ver = "2.3.9"
http-client-ver = "5.2.1"
iceberg-ver = "1.6.1"
jackson-ver = "2.15.0"
jetty-server-ver = "9.4.57.v20241219"
jetty-http-ver = "12.0.12"
junit-ver = "5.10.0"
kafka-ver = "3.7.2"
logback-ver = "1.5.19"
netty-ver = "4.1.118.Final"
netty-codec-http-ver = "4.1.125.Final"
parquet-avro-ver = "1.15.2"
protobuf-java-ver = "3.25.5"
slf4j-ver = "1.7.36"
testcontainers-ver = "1.17.6"
libthrift-ver = "0.15.0"
zookeeper-ver = "3.8.4"


[libraries]
ant = { module = "org.apache.ant:ant", version.ref = "ant-ver" }
avro = { module = "org.apache.avro:avro", version.ref = "avro-ver" }
aircompressor = { module = "io.airlift:aircompressor", version.ref = "aircompressor" }
commonsBeanutils = { module = "commons-beanutils:commons-beanutils", version.ref = "commonsBeanutils-ver" }
commonsCompress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3-ver" }
derby = { module = "org.apache.derby:derby", version.ref = "derby-ver" }
bson = { module = "org.mongodb:bson", version.ref = "bson-ver"}
guava = { module = "com.google.guava:guava", version.ref = "guava-ver" }
hadoop-client = { module = "org.apache.hadoop:hadoop-client", version.ref = "hadoop-ver" }
hadoop-common = { module = "org.apache.hadoop:hadoop-common", version.ref = "hadoop-ver" }
hive-metastore = { module = "org.apache.hive:hive-metastore", version.ref = "hive-ver" }
iceberg-api = { module = "org.apache.iceberg:iceberg-api", version.ref = "iceberg-ver" }
iceberg-aws = { module = "org.apache.iceberg:iceberg-aws", version.ref = "iceberg-ver" }
iceberg-azure = { module = "org.apache.iceberg:iceberg-azure", version.ref = "iceberg-ver" }
iceberg-common = { module = "org.apache.iceberg:iceberg-common", version.ref = "iceberg-ver" }
iceberg-core = { module = "org.apache.iceberg:iceberg-core", version.ref = "iceberg-ver" }
iceberg-data = { module = "org.apache.iceberg:iceberg-data", version.ref = "iceberg-ver" }
iceberg-gcp = { module = "org.apache.iceberg:iceberg-gcp", version.ref = "iceberg-ver" }
iceberg-gcp-bundle = { module = "org.apache.iceberg:iceberg-gcp-bundle", version.ref = "iceberg-ver" }
iceberg-guava = { module = "org.apache.iceberg:iceberg-bundled-guava", version.ref = "iceberg-ver" }
iceberg-hive-metastore = { module = "org.apache.iceberg:iceberg-hive-metastore", version.ref = "iceberg-ver" }
iceberg-kafka-connect-events = {module = "org.apache.iceberg:iceberg-kafka-connect-events", version.ref = "iceberg-ver"}
iceberg-nessie = { module = "org.apache.iceberg:iceberg-nessie", version.ref = "iceberg-ver" }
iceberg-orc = { module = "org.apache.iceberg:iceberg-orc", version.ref = "iceberg-ver" }
iceberg-parquet = { module = "org.apache.iceberg:iceberg-parquet", version.ref = "iceberg-ver" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson-ver" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-ver" }
jetty-http = { module = "org.eclipse.jetty:jetty-http", version.ref = "jetty-http-ver" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty-server-ver" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-ver" }
kafka-connect-api = { module = "org.apache.kafka:connect-api", version.ref = "kafka-ver" }
kafka-connect-json = { module = "org.apache.kafka:connect-json", version.ref = "kafka-ver" }
kafka-connect-transforms = { module = "org.apache.kafka:connect-transforms", version.ref = "kafka-ver" }
libthrift = { module = "org.apache.thrift:libthrift", version.ref = "libthrift-ver" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty-codec-http-ver" }
netty-common = { module = "io.netty:netty-common", version.ref = "netty-ver" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty-ver" }
parquet-avro = { module = "org.apache.parquet:parquet-avro", version.ref = "parquet-avro-ver" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf-java-ver" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-ver" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-ver" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback-ver" }
zookeeper = { module = "org.apache.zookeeper:zookeeper", version.ref = "zookeeper-ver" }

# test dependencies
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj-ver" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility-ver" }
http-client = { module =  "org.apache.httpcomponents.client5:httpclient5", version.ref = "http-client-ver" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-ver" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-ver" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-ver" }
mockito = "org.mockito:mockito-core:4.8.1"
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers-ver" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers-ver" }

spotless-gradle = "com.diffplug.spotless:spotless-plugin-gradle:6.13.0"
palantir-gradle = "com.palantir.baseline:gradle-baseline-java:4.42.0"


[bundles]
iceberg = ["iceberg-api", "iceberg-common", "iceberg-core", "iceberg-data", "iceberg-guava", "iceberg-orc", "iceberg-parquet", "iceberg-kafka-connect-events"]
iceberg-ext = ["iceberg-aws", "iceberg-azure", "iceberg-gcp","iceberg-gcp-bundle", "iceberg-nessie"]
jackson = ["jackson-core", "jackson-databind"]
kafka-connect = ["kafka-clients", "kafka-connect-api", "kafka-connect-json", "kafka-connect-transforms"]


[plugins]
nebula-release = "nebula.release:17.2.2"
